# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ralsina/Desktop/proyectos/urssus/trunk/urssus/ui/main.ui'
#
# Created: Fri Dec 11 13:50:03 2009
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(65, 141, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 141, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/urssus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtGui.QSplitter(self.centralWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.feedTree = FeedTree(self.splitter_2)
        self.feedTree.setFocusPolicy(QtCore.Qt.NoFocus)
        self.feedTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.feedTree.setDragEnabled(True)
        self.feedTree.setDragDropOverwriteMode(False)
        self.feedTree.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.feedTree.setAlternatingRowColors(True)
        self.feedTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.feedTree.setTextElideMode(QtCore.Qt.ElideRight)
        self.feedTree.setUniformRowHeights(True)
        self.feedTree.setAllColumnsShowFocus(True)
        self.feedTree.setColumnCount(2)
        self.feedTree.setObjectName("feedTree")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.posts = QtGui.QTreeView(self.splitter)
        self.posts.setFocusPolicy(QtCore.Qt.NoFocus)
        self.posts.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.posts.setFrameShape(QtGui.QFrame.StyledPanel)
        self.posts.setFrameShadow(QtGui.QFrame.Plain)
        self.posts.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.posts.setAlternatingRowColors(True)
        self.posts.setRootIsDecorated(False)
        self.posts.setUniformRowHeights(False)
        self.posts.setItemsExpandable(False)
        self.posts.setSortingEnabled(True)
        self.posts.setAnimated(True)
        self.posts.setAllColumnsShowFocus(True)
        self.posts.setExpandsOnDoubleClick(False)
        self.posts.setObjectName("posts")
        self.view_container = QtGui.QFrame(self.splitter)
        self.view_container.setFrameShape(QtGui.QFrame.StyledPanel)
        self.view_container.setFrameShadow(QtGui.QFrame.Plain)
        self.view_container.setObjectName("view_container")
        self.verticalLayout = QtGui.QVBoxLayout(self.view_container)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.view = QtWebKit.QWebView(self.view_container)
        self.view.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.view.setUrl(QtCore.QUrl("about:blank"))
        self.view.setObjectName("view")
        self.verticalLayout.addWidget(self.view)
        self.horizontalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setWindowIcon(icon)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuFeed = QtGui.QMenu(self.menuBar)
        self.menuFeed.setObjectName("menuFeed")
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Go = QtGui.QMenu(self.menuBar)
        self.menu_Go.setObjectName("menu_Go")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_View = QtGui.QMenu(self.menuBar)
        self.menu_View.setObjectName("menu_View")
        self.menu_View_Mode = QtGui.QMenu(self.menu_View)
        self.menu_View_Mode.setObjectName("menu_View_Mode")
        self.menuToolbars = QtGui.QMenu(self.menu_View)
        self.menuToolbars.setObjectName("menuToolbars")
        self.menu_Zoom = QtGui.QMenu(self.menu_View)
        self.menu_Zoom.setObjectName("menu_Zoom")
        self.menu_Edit = QtGui.QMenu(self.menuBar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menuArticle = QtGui.QMenu(self.menuBar)
        self.menuArticle.setObjectName("menuArticle")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.filterBar = QtGui.QToolBar(MainWindow)
        self.filterBar.setObjectName("filterBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.filterBar)
        self.searchBar = QtGui.QToolBar(MainWindow)
        self.searchBar.setMovable(False)
        self.searchBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea)
        self.searchBar.setFloatable(False)
        self.searchBar.setObjectName("searchBar")
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.searchBar)
        self.actionFetch_Feed = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/1downarrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFetch_Feed.setIcon(icon1)
        self.actionFetch_Feed.setObjectName("actionFetch_Feed")
        self.actionFetch_All_Feeds = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/2downarrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFetch_All_Feeds.setIcon(icon2)
        self.actionFetch_All_Feeds.setObjectName("actionFetch_All_Feeds")
        self.actionAbort_Fetches = QtGui.QAction(MainWindow)
        self.actionAbort_Fetches.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbort_Fetches.setIcon(icon3)
        self.actionAbort_Fetches.setObjectName("actionAbort_Fetches")
        self.actionMark_Feed_as_Read = QtGui.QAction(MainWindow)
        self.actionMark_Feed_as_Read.setEnabled(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/apply.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMark_Feed_as_Read.setIcon(icon4)
        self.actionMark_Feed_as_Read.setObjectName("actionMark_Feed_as_Read")
        self.actionImport_Feeds = QtGui.QAction(MainWindow)
        self.actionImport_Feeds.setObjectName("actionImport_Feeds")
        self.actionExport_Feeds = QtGui.QAction(MainWindow)
        self.actionExport_Feeds.setObjectName("actionExport_Feeds")
        self.actionQuit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon5)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNext_Article = QtGui.QAction(MainWindow)
        self.actionNext_Article.setObjectName("actionNext_Article")
        self.actionNext_Unread_Article = QtGui.QAction(MainWindow)
        self.actionNext_Unread_Article.setObjectName("actionNext_Unread_Article")
        self.actionNext_Feed = QtGui.QAction(MainWindow)
        self.actionNext_Feed.setObjectName("actionNext_Feed")
        self.actionNext_Unread_Feed = QtGui.QAction(MainWindow)
        self.actionNext_Unread_Feed.setObjectName("actionNext_Unread_Feed")
        self.actionAbout_uRSSus = QtGui.QAction(MainWindow)
        self.actionAbout_uRSSus.setIcon(icon)
        self.actionAbout_uRSSus.setObjectName("actionAbout_uRSSus")
        self.actionIncrease_Font_Sizes = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/viewmag+.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIncrease_Font_Sizes.setIcon(icon6)
        self.actionIncrease_Font_Sizes.setObjectName("actionIncrease_Font_Sizes")
        self.actionDecrease_Font_Sizes = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/viewmag-.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDecrease_Font_Sizes.setIcon(icon7)
        self.actionDecrease_Font_Sizes.setObjectName("actionDecrease_Font_Sizes")
        self.actionStatus_Bar = QtGui.QAction(MainWindow)
        self.actionStatus_Bar.setCheckable(True)
        self.actionStatus_Bar.setChecked(True)
        self.actionStatus_Bar.setObjectName("actionStatus_Bar")
        self.actionPrevious_Feed = QtGui.QAction(MainWindow)
        self.actionPrevious_Feed.setObjectName("actionPrevious_Feed")
        self.actionPrevious_Unread_Feed = QtGui.QAction(MainWindow)
        self.actionPrevious_Unread_Feed.setObjectName("actionPrevious_Unread_Feed")
        self.actionPrevious_Article = QtGui.QAction(MainWindow)
        self.actionPrevious_Article.setObjectName("actionPrevious_Article")
        self.actionPrevious_Unread_Article = QtGui.QAction(MainWindow)
        self.actionPrevious_Unread_Article.setObjectName("actionPrevious_Unread_Article")
        self.actionFind = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/find.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon8)
        self.actionFind.setObjectName("actionFind")
        self.actionFind_Again = QtGui.QAction(MainWindow)
        self.actionFind_Again.setObjectName("actionFind_Again")
        self.actionShow_Only_Unread_Feeds = QtGui.QAction(MainWindow)
        self.actionShow_Only_Unread_Feeds.setCheckable(True)
        self.actionShow_Only_Unread_Feeds.setObjectName("actionShow_Only_Unread_Feeds")
        self.actionOpen_Homepage = QtGui.QAction(MainWindow)
        self.actionOpen_Homepage.setObjectName("actionOpen_Homepage")
        self.actionDelete_Feed = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/editdelete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_Feed.setIcon(icon9)
        self.actionDelete_Feed.setObjectName("actionDelete_Feed")
        self.actionAdd_Feed = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/filenew.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Feed.setIcon(icon10)
        self.actionAdd_Feed.setObjectName("actionAdd_Feed")
        self.actionNew_Folder = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/folder_new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Folder.setIcon(icon11)
        self.actionNew_Folder.setObjectName("actionNew_Folder")
        self.actionEdit_Feed = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Feed.setIcon(icon12)
        self.actionEdit_Feed.setObjectName("actionEdit_Feed")
        self.actionMark_as_Read = QtGui.QAction(MainWindow)
        self.actionMark_as_Read.setObjectName("actionMark_as_Read")
        self.actionMark_as_Unread = QtGui.QAction(MainWindow)
        self.actionMark_as_Unread.setObjectName("actionMark_as_Unread")
        self.actionMark_as_Important = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/star.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMark_as_Important.setIcon(icon13)
        self.actionMark_as_Important.setObjectName("actionMark_as_Important")
        self.actionDelete_Article = QtGui.QAction(MainWindow)
        self.actionDelete_Article.setIcon(icon9)
        self.actionDelete_Article.setObjectName("actionDelete_Article")
        self.actionOpen_in_Browser = QtGui.QAction(MainWindow)
        self.actionOpen_in_Browser.setObjectName("actionOpen_in_Browser")
        self.actionRemove_Important_Mark = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/star2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_Important_Mark.setIcon(icon14)
        self.actionRemove_Important_Mark.setObjectName("actionRemove_Important_Mark")
        self.actionExpire_Feed = QtGui.QAction(MainWindow)
        self.actionExpire_Feed.setObjectName("actionExpire_Feed")
        self.actionTechnorati_Top_10 = QtGui.QAction(MainWindow)
        self.actionTechnorati_Top_10.setObjectName("actionTechnorati_Top_10")
        self.actionNormal_View = QtGui.QAction(MainWindow)
        self.actionNormal_View.setEnabled(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/view_top_bottom.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNormal_View.setIcon(icon15)
        self.actionNormal_View.setObjectName("actionNormal_View")
        self.actionCombined_View = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/view_detailed.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCombined_View.setIcon(icon16)
        self.actionCombined_View.setObjectName("actionCombined_View")
        self.actionWidescreen_View = QtGui.QAction(MainWindow)
        self.actionWidescreen_View.setCheckable(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/view_left_right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWidescreen_View.setIcon(icon17)
        self.actionWidescreen_View.setObjectName("actionWidescreen_View")
        self.actionMain_Toolbar = QtGui.QAction(MainWindow)
        self.actionMain_Toolbar.setCheckable(True)
        self.actionMain_Toolbar.setChecked(True)
        self.actionMain_Toolbar.setObjectName("actionMain_Toolbar")
        self.actionFilter_Toolbar = QtGui.QAction(MainWindow)
        self.actionFilter_Toolbar.setCheckable(True)
        self.actionFilter_Toolbar.setChecked(True)
        self.actionFilter_Toolbar.setObjectName("actionFilter_Toolbar")
        self.actionZoom_Reset = QtGui.QAction(MainWindow)
        self.actionZoom_Reset.setObjectName("actionZoom_Reset")
        self.actionShort_Feed_List = QtGui.QAction(MainWindow)
        self.actionShort_Feed_List.setCheckable(True)
        self.actionShort_Feed_List.setObjectName("actionShort_Feed_List")
        self.actionFancy_View = QtGui.QAction(MainWindow)
        self.actionFancy_View.setIcon(icon16)
        self.actionFancy_View.setObjectName("actionFancy_View")
        self.actionPost_to_Twitter = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/twitter.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPost_to_Twitter.setIcon(icon18)
        self.actionPost_to_Twitter.setObjectName("actionPost_to_Twitter")
        self.actionFull_Screen = QtGui.QAction(MainWindow)
        self.actionFull_Screen.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/window_fullscreen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFull_Screen.setIcon(icon19)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.actionShow_Menu_Bar = QtGui.QAction(MainWindow)
        self.actionShow_Menu_Bar.setCheckable(True)
        self.actionShow_Menu_Bar.setChecked(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/menubar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Menu_Bar.setIcon(icon20)
        self.actionShow_Menu_Bar.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionShow_Menu_Bar.setObjectName("actionShow_Menu_Bar")
        self.actionImport_From_Google_Reader = QtGui.QAction(MainWindow)
        self.actionImport_From_Google_Reader.setObjectName("actionImport_From_Google_Reader")
        self.actionReport_Bug = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/bug.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport_Bug.setIcon(icon21)
        self.actionReport_Bug.setObjectName("actionReport_Bug")
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/configure.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon22)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionShowStarredColumn = QtGui.QAction(MainWindow)
        self.actionShowStarredColumn.setCheckable(True)
        self.actionShowStarredColumn.setChecked(True)
        self.actionShowStarredColumn.setObjectName("actionShowStarredColumn")
        self.actionShowFeedColumn = QtGui.QAction(MainWindow)
        self.actionShowFeedColumn.setCheckable(True)
        self.actionShowFeedColumn.setObjectName("actionShowFeedColumn")
        self.actionShowDateColumn = QtGui.QAction(MainWindow)
        self.actionShowDateColumn.setCheckable(True)
        self.actionShowDateColumn.setChecked(True)
        self.actionShowDateColumn.setObjectName("actionShowDateColumn")
        self.actionSync_Bookmarks_To_Web = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/sync.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSync_Bookmarks_To_Web.setIcon(icon23)
        self.actionSync_Bookmarks_To_Web.setObjectName("actionSync_Bookmarks_To_Web")
        self.actionTag_Article = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/tag.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTag_Article.setIcon(icon24)
        self.actionTag_Article.setObjectName("actionTag_Article")
        self.action_Handbook = QtGui.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Handbook.setIcon(icon25)
        self.action_Handbook.setObjectName("action_Handbook")
        self.actionCopy_Article_URL = QtGui.QAction(MainWindow)
        self.actionCopy_Article_URL.setObjectName("actionCopy_Article_URL")
        self.toolBar.addAction(self.actionFetch_Feed)
        self.toolBar.addAction(self.actionFetch_All_Feeds)
        self.toolBar.addAction(self.actionAbort_Fetches)
        self.toolBar.addAction(self.actionMark_Feed_as_Read)
        self.menuFeed.addSeparator()
        self.menuFeed.addAction(self.actionAdd_Feed)
        self.menuFeed.addAction(self.actionNew_Folder)
        self.menuFeed.addSeparator()
        self.menuFeed.addAction(self.actionMark_Feed_as_Read)
        self.menuFeed.addSeparator()
        self.menuFeed.addAction(self.actionFetch_Feed)
        self.menuFeed.addAction(self.actionFetch_All_Feeds)
        self.menuFeed.addAction(self.actionAbort_Fetches)
        self.menuFeed.addSeparator()
        self.menuFeed.addAction(self.actionEdit_Feed)
        self.menuFeed.addAction(self.actionExpire_Feed)
        self.menuFeed.addAction(self.actionDelete_Feed)
        self.menu_File.addAction(self.actionImport_Feeds)
        self.menu_File.addAction(self.actionExport_Feeds)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionTechnorati_Top_10)
        self.menu_File.addAction(self.actionImport_From_Google_Reader)
        self.menu_File.addAction(self.actionSync_Bookmarks_To_Web)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Go.addSeparator()
        self.menu_Go.addAction(self.actionPrevious_Article)
        self.menu_Go.addAction(self.actionPrevious_Unread_Article)
        self.menu_Go.addAction(self.actionNext_Article)
        self.menu_Go.addAction(self.actionNext_Unread_Article)
        self.menu_Go.addSeparator()
        self.menu_Go.addAction(self.actionPrevious_Feed)
        self.menu_Go.addAction(self.actionPrevious_Unread_Feed)
        self.menu_Go.addAction(self.actionNext_Feed)
        self.menu_Go.addAction(self.actionNext_Unread_Feed)
        self.menuHelp.addAction(self.action_Handbook)
        self.menuHelp.addAction(self.actionAbout_uRSSus)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionReport_Bug)
        self.menu_View_Mode.addAction(self.actionNormal_View)
        self.menu_View_Mode.addAction(self.actionWidescreen_View)
        self.menu_View_Mode.addAction(self.actionCombined_View)
        self.menu_View_Mode.addAction(self.actionFancy_View)
        self.menu_View_Mode.addSeparator()
        self.menu_View_Mode.addAction(self.actionShort_Feed_List)
        self.menuToolbars.addAction(self.actionMain_Toolbar)
        self.menuToolbars.addAction(self.actionFilter_Toolbar)
        self.menu_Zoom.addAction(self.actionIncrease_Font_Sizes)
        self.menu_Zoom.addAction(self.actionDecrease_Font_Sizes)
        self.menu_Zoom.addSeparator()
        self.menu_Zoom.addAction(self.actionZoom_Reset)
        self.menu_View.addAction(self.menuToolbars.menuAction())
        self.menu_View.addAction(self.actionShow_Menu_Bar)
        self.menu_View.addAction(self.actionStatus_Bar)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.actionShow_Only_Unread_Feeds)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.menu_View_Mode.menuAction())
        self.menu_View.addAction(self.menu_Zoom.menuAction())
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.actionFull_Screen)
        self.menu_Edit.addAction(self.actionFind)
        self.menu_Edit.addAction(self.actionFind_Again)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionPreferences)
        self.menuArticle.addAction(self.actionOpen_in_Browser)
        self.menuArticle.addAction(self.actionCopy_Article_URL)
        self.menuArticle.addSeparator()
        self.menuArticle.addAction(self.actionTag_Article)
        self.menuArticle.addAction(self.actionMark_as_Read)
        self.menuArticle.addAction(self.actionMark_as_Unread)
        self.menuArticle.addSeparator()
        self.menuArticle.addAction(self.actionPost_to_Twitter)
        self.menuArticle.addSeparator()
        self.menuArticle.addAction(self.actionDelete_Article)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Edit.menuAction())
        self.menuBar.addAction(self.menu_View.menuAction())
        self.menuBar.addAction(self.menu_Go.menuAction())
        self.menuBar.addAction(self.menuFeed.menuAction())
        self.menuBar.addAction(self.menuArticle.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        MainWindow.addAction(self.actionShow_Menu_Bar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionMain_Toolbar, QtCore.SIGNAL("triggered(bool)"), self.toolBar.setVisible)
        QtCore.QObject.connect(self.actionFilter_Toolbar, QtCore.SIGNAL("triggered(bool)"), self.filterBar.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "uRSSus", None, QtGui.QApplication.UnicodeUTF8))
        self.feedTree.setSortingEnabled(False)
        self.feedTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.feedTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Unread", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFeed.setTitle(QtGui.QApplication.translate("MainWindow", "Fee&d", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Go.setTitle(QtGui.QApplication.translate("MainWindow", "&Go", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View_Mode.setTitle(QtGui.QApplication.translate("MainWindow", "&View Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToolbars.setTitle(QtGui.QApplication.translate("MainWindow", "Toolbars", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Zoom.setTitle(QtGui.QApplication.translate("MainWindow", "&Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArticle.setTitle(QtGui.QApplication.translate("MainWindow", "&Article", None, QtGui.QApplication.UnicodeUTF8))
        self.filterBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.searchBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFetch_Feed.setText(QtGui.QApplication.translate("MainWindow", "Fetch Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFetch_Feed.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFetch_All_Feeds.setText(QtGui.QApplication.translate("MainWindow", "Fetch All Feeds", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFetch_All_Feeds.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbort_Fetches.setText(QtGui.QApplication.translate("MainWindow", "Abort Fetches", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbort_Fetches.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_Feed_as_Read.setText(QtGui.QApplication.translate("MainWindow", "Mark Feed as Read", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_Feed_as_Read.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Feeds.setText(QtGui.QApplication.translate("MainWindow", "&Import Feeds...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Feeds.setText(QtGui.QApplication.translate("MainWindow", "&Export Feeds...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Article.setText(QtGui.QApplication.translate("MainWindow", "&Next Article", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Article.setShortcut(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Unread_Article.setText(QtGui.QApplication.translate("MainWindow", "Ne&xt Unread Article", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Unread_Article.setShortcut(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Feed.setText(QtGui.QApplication.translate("MainWindow", "Next &Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Feed.setShortcut(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Unread_Feed.setText(QtGui.QApplication.translate("MainWindow", "N&ext Unread Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Unread_Feed.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt++", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_uRSSus.setText(QtGui.QApplication.translate("MainWindow", "&About uRSSus...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncrease_Font_Sizes.setText(QtGui.QApplication.translate("MainWindow", "Zoom &In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncrease_Font_Sizes.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl++", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecrease_Font_Sizes.setText(QtGui.QApplication.translate("MainWindow", "Zoom &Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecrease_Font_Sizes.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatus_Bar.setText(QtGui.QApplication.translate("MainWindow", "Status Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Feed.setText(QtGui.QApplication.translate("MainWindow", "P&revious Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Feed.setShortcut(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Unread_Feed.setText(QtGui.QApplication.translate("MainWindow", "Prev&ious Unread Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Unread_Feed.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Article.setText(QtGui.QApplication.translate("MainWindow", "&Previous Article", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Article.setShortcut(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Unread_Article.setText(QtGui.QApplication.translate("MainWindow", "Pre&vious Unread Article", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Unread_Article.setShortcut(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setText(QtGui.QApplication.translate("MainWindow", "&Find", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Again.setText(QtGui.QApplication.translate("MainWindow", "Find Again", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Again.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Only_Unread_Feeds.setText(QtGui.QApplication.translate("MainWindow", "Show Only Unread Feeds", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Homepage.setText(QtGui.QApplication.translate("MainWindow", "Open Homepage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Homepage.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Feed.setText(QtGui.QApplication.translate("MainWindow", "&Delete Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Feed.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Feed.setText(QtGui.QApplication.translate("MainWindow", "Add Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Feed.setShortcut(QtGui.QApplication.translate("MainWindow", "Ins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Folder.setText(QtGui.QApplication.translate("MainWindow", "New Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Folder.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+Ins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Feed.setText(QtGui.QApplication.translate("MainWindow", "&Edit Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Feed.setShortcut(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_as_Read.setText(QtGui.QApplication.translate("MainWindow", "Mark as Read", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_as_Read.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_as_Unread.setText(QtGui.QApplication.translate("MainWindow", "Mark as Unread", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_as_Unread.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_as_Important.setText(QtGui.QApplication.translate("MainWindow", "Mark as Important", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_as_Important.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Article.setText(QtGui.QApplication.translate("MainWindow", "Delete Article", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Article.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_in_Browser.setText(QtGui.QApplication.translate("MainWindow", "Open in Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_in_Browser.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Important_Mark.setText(QtGui.QApplication.translate("MainWindow", "Remove Important Mark", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Important_Mark.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExpire_Feed.setText(QtGui.QApplication.translate("MainWindow", "Expire Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTechnorati_Top_10.setText(QtGui.QApplication.translate("MainWindow", "Import Technorati Top 10", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormal_View.setText(QtGui.QApplication.translate("MainWindow", "Normal View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCombined_View.setText(QtGui.QApplication.translate("MainWindow", "Combined View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWidescreen_View.setText(QtGui.QApplication.translate("MainWindow", "Widescreen View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMain_Toolbar.setText(QtGui.QApplication.translate("MainWindow", "Main Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilter_Toolbar.setText(QtGui.QApplication.translate("MainWindow", "Filter Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Reset.setText(QtGui.QApplication.translate("MainWindow", "&Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Reset.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+0", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShort_Feed_List.setText(QtGui.QApplication.translate("MainWindow", "Short Feed List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFancy_View.setText(QtGui.QApplication.translate("MainWindow", "Fancy View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPost_to_Twitter.setText(QtGui.QApplication.translate("MainWindow", "Post to Twitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Screen.setText(QtGui.QApplication.translate("MainWindow", "&Full Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Screen.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Menu_Bar.setText(QtGui.QApplication.translate("MainWindow", "Show Menu Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Menu_Bar.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_From_Google_Reader.setText(QtGui.QApplication.translate("MainWindow", "Import From Google Reader", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_Bug.setText(QtGui.QApplication.translate("MainWindow", "Report Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowStarredColumn.setText(QtGui.QApplication.translate("MainWindow", "Starred", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowFeedColumn.setText(QtGui.QApplication.translate("MainWindow", "Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDateColumn.setText(QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSync_Bookmarks_To_Web.setText(QtGui.QApplication.translate("MainWindow", "Sync Bookmarks To Web", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTag_Article.setText(QtGui.QApplication.translate("MainWindow", "Tag Article", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTag_Article.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Handbook.setText(QtGui.QApplication.translate("MainWindow", "uRSSus Handbook", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Handbook.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_Article_URL.setText(QtGui.QApplication.translate("MainWindow", "Copy URL", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
from urssus.feedtree import FeedTree
import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

